name: Terraform Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # --- FAST CHECKS (always run) ---
      - name: Terraform Format Check
        run: terraform fmt -recursive -check

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: tflint --recursive

      # --- SECURITY CHECKS (only on main) ---
      - name: Run Checkov
        if: github.ref == 'refs/heads/main'
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
